import { Metadata } from 'next';
import Link from 'next/link';
import { GUIDES_DATA } from '@/lib/guides-data';

export const metadata: Metadata = {
  title: 'How to Start a Business in Bali | Ultimate Guide 2025',
  description: 'The definitive 5000+ word guide to starting a business in Bali. Covers PT PMA registration, business licensing, tax, costs, and everything foreign investors need to know.',
  alternates: { canonical: 'https://balihelp.id/business-guides/how-to-start-a-business-in-bali' },
  openGraph: {
    type: 'article',
    title: 'How to Start a Business in Bali | Ultimate Guide',
    description: 'The definitive guide to starting a business in Bali for foreign investors.',
    url: 'https://balihelp.id/business-guides/how-to-start-a-business-in-bali',
    siteName: 'Bali Help',
    images: [{ url: 'https://balihelp.id/og-image.webp', width: 1200, height: 630, alt: 'Start Business Bali Guide' }],
  },
  twitter: { card: 'summary_large_image', title: 'How to Start a Business in Bali | Ultimate Guide', description: 'The definitive guide to starting a business in Bali.', images: ['https://balihelp.id/og-image.webp'] },
};

const sections = [
  { id: 'introduction', title: 'Introduction to Starting a Business in Bali', content: `Bali has emerged as one of the most exciting destinations for international entrepreneurs and investors. With its vibrant digital nomad community, booming tourism sector, world-class infrastructure, and exceptional quality of life, Bali offers a unique blend of business opportunity and lifestyle that few other locations can match.\n\nThis ultimate guide covers everything you need to know about establishing a legally compliant business in Bali and Indonesia. Whether you are a seasoned investor looking to expand into Southeast Asia or a first-time entrepreneur drawn to Bali's creative energy, this guide provides the practical knowledge you need to make informed decisions.\n\nBali Help, operated by PT Indonesian Visas Agency, has assisted hundreds of foreign investors in navigating the Indonesian business landscape. This guide draws on that experience to provide accurate, actionable information about company formation, licensing, taxation, and operational setup in Bali.` },
  { id: 'why-bali', title: 'Why Bali Attracts International Entrepreneurs', content: `Bali attracts entrepreneurs from around the world for several compelling reasons. The island offers a cost of living significantly lower than major Western cities, excellent international flight connectivity, reliable internet infrastructure, and a thriving community of like-minded business professionals.\n\nThe Indonesian economy is the largest in Southeast Asia, with a GDP exceeding $1.3 trillion and a population of over 270 million people. This enormous domestic market provides vast opportunities for businesses ranging from technology and digital services to tourism, food and beverage, and wellness.\n\nBali specifically benefits from its status as Indonesia's premier tourism destination, receiving over 6 million international visitors annually before the pandemic, with numbers rapidly recovering. This tourist flow creates a reliable consumer base for hospitality, retail, and service businesses.\n\nAdditionally, the Indonesian government has actively encouraged foreign investment through regulatory reforms, particularly the Omnibus Law on Job Creation (2020), which simplified business registration, reduced bureaucratic barriers, and expanded sectors open to foreign ownership.\n\nThe co-working culture in Bali is among the most developed in Asia, with dozens of professional spaces in Canggu, Seminyak, Ubud, and Sanur. This ecosystem provides networking opportunities, mentorship, and collaboration potential that accelerate business growth.` },
  { id: 'legal-framework', title: 'Legal Framework for Foreign Investors', content: `Indonesia's legal framework for foreign investment is comprehensive and well-established. The primary legislation governing foreign business activities includes the Company Law (No. 40 of 2007), the Investment Law (No. 25 of 2007), and the Omnibus Law on Job Creation (No. 11 of 2020).\n\nForeign investors are regulated by the Ministry of Investment (formerly BKPM - the Investment Coordinating Board), which oversees all foreign direct investment activities. The ministry maintains the Positive Investment List, which categorizes business sectors by their openness to foreign ownership.\n\nThe Omnibus Law introduced significant reforms that benefit foreign investors, including simplified licensing procedures, reduced capital requirements for certain sectors, streamlined labor regulations, and a more transparent regulatory environment. These changes have made Indonesia increasingly competitive as a destination for foreign direct investment.\n\nIt is important to understand that while Indonesia welcomes foreign investment, it also maintains protective regulations in certain sectors deemed strategically important. Agriculture, certain media activities, small-scale retail, and some transportation services may have restrictions on foreign participation.\n\nAll business activities in Indonesia must be classified under the KBLI (Klasifikasi Baku Lapangan Usaha Indonesia) system, which determines the applicable regulations, licensing requirements, and foreign ownership limits for each type of business activity.` },
  { id: 'pt-pma', title: 'Understanding PT PMA Companies', content: `PT PMA (Penanaman Modal Asing) is the standard legal entity for foreign-owned businesses in Indonesia. The term translates to "Foreign Capital Investment Limited Liability Company" and represents the most common vehicle for foreign entrepreneurs to establish a legally compliant business presence.\n\nA PT PMA functions as a separate legal entity, providing limited liability protection to its shareholders. This means that shareholders' personal assets are generally protected from the company's debts and liabilities, similar to LLC or corporation structures in other countries.\n\nKey characteristics of PT PMA include: minimum two shareholders (individuals or legal entities), at least one director and one commissioner, minimum authorized capital of IDR 10 billion with paid-up capital of IDR 2.5 billion, and the ability to engage in commercial activities across approved business sectors.\n\nThe PT PMA structure allows foreigners to own up to 100% of the company in many sectors, though some industries require Indonesian investment partners with specific ownership percentages. It is critical to verify the current regulations for your specific business activities before proceeding with registration.\n\nPT PMA companies can hire foreign employees by sponsoring KITAS (Kartu Izin Tinggal Terbatas) work permits, open corporate bank accounts, issue invoices, and engage in all standard commercial activities. This makes it the most versatile and recommended structure for serious foreign investors.` },
  { id: 'licensing', title: 'Business Licensing System in Indonesia', content: `Indonesia's business licensing system has undergone significant modernization in recent years, primarily through the introduction of the OSS (Online Single Submission) platform. All business licenses are now processed through this centralized digital system, replacing the previously fragmented process that required visiting multiple government offices.\n\nThe NIB (Nomor Induk Berusaha) or Business Identification Number is the foundational license that every company must obtain. The NIB serves as the company's primary business identity and is required before any commercial activities can commence. It replaces several previously separate registrations including TDP, API, and Angka Pengenal Importir.\n\nBeyond the NIB, companies may need additional sector-specific licenses depending on their KBLI codes. These include commercial licenses (for trading activities), operational licenses (for service and operational activities), and special permits (for regulated industries such as food production, healthcare, or education).\n\nThe licensing process through OSS has been designed to be efficient and transparent, with most applications processed within days rather than weeks. However, some sector-specific licenses may require physical inspections or additional documentation, which can extend the timeline.\n\nIt is crucial to select the correct KBLI codes during registration, as these codes determine your licensing requirements and foreign ownership eligibility. Changing KBLI codes after registration is possible but requires additional procedures and may affect your existing licenses.` },
  { id: 'oss', title: 'OSS Licensing Platform', content: `The Online Single Submission (OSS) system, managed by the Ministry of Investment, is Indonesia's integrated digital platform for all business licensing activities. Launched in 2018 and significantly upgraded with OSS RBA (Risk-Based Approach) in 2021, the system streamlines the licensing process by categorizing businesses based on their risk level.\n\nBusinesses are classified into four risk categories: low risk (requiring only NIB), medium-low risk (requiring NIB plus standard certificate), medium-high risk (requiring NIB plus standard certificate with verification), and high risk (requiring NIB plus a full permit). The risk classification is automatically determined by the KBLI codes selected during registration.\n\nThe OSS platform integrates with multiple government agencies, eliminating the need for separate applications to different ministries. This integration includes the tax authority, immigration department, customs office, and various sectoral regulators.\n\nTo use the OSS system, you will need a registered company (company deed approved by MENKUMHAM), a director with an active NPWP (tax ID), and valid KBLI codes. The registration process is conducted online and typically takes 1-3 business days for basic NIB issuance.\n\nWhile the OSS system has greatly simplified the process, navigating it correctly still requires understanding of Indonesian regulatory terminology and classification systems. Professional service providers can ensure accurate and efficient registration.` },
  { id: 'nib', title: 'NIB Registration Explained', content: `NIB (Nomor Induk Berusaha) is Indonesia's Business Identification Number, serving as the primary business license for all companies operating in the country. Since its introduction in 2018, the NIB has replaced several previously separate identification numbers and registrations.\n\nThe NIB functions simultaneously as: a company registration certificate, a trade registration number, an import identification number (for companies engaged in import activities), and a customs registration (when applicable). This consolidation has significantly simplified the administrative requirements for businesses.\n\nObtaining an NIB is mandatory before a company can legally commence commercial activities. The registration is processed through the OSS system and typically takes 1-3 business days when all required documentation is complete and accurate.\n\nRequired information for NIB registration includes: company legal entity details, KBLI codes for all business activities, investment plan, projected workforce numbers, business location details, and shareholder/director information. The accuracy of this information is critical as it determines subsequent licensing requirements.\n\nThe NIB remains valid as long as the company maintains compliance with its reporting obligations and regulatory requirements. Companies must update their NIB registration whenever there are changes to their business activities, ownership structure, or other registered information.` },
  { id: 'tax', title: 'Corporate Tax Structure', content: `Indonesia applies a standard corporate income tax rate of 22% on taxable income for all companies, including PT PMA entities. This rate was reduced from 25% as part of the government's effort to attract investment and improve competitiveness.\n\nSmall and medium enterprises (SMEs) may qualify for reduced tax rates. Companies with annual gross revenue below IDR 50 billion receive a 50% discount on the standard rate for the portion of taxable income corresponding to their gross revenue. Newly registered PT PMA companies may also qualify for tax incentives in certain priority sectors.\n\nIndonesia applies a self-assessment tax system, meaning companies are responsible for calculating, paying, and reporting their own tax obligations. Monthly tax obligations include income tax withholding (PPh 21 for employees, PPh 23 for services, PPh 26 for foreign payments), and VAT (PPN at 11%) for PKP-registered companies.\n\nAnnual corporate tax returns must be filed by April 30 of the following year. Monthly tax returns are due by the 20th of the following month. Late filing penalties range from IDR 100,000 to IDR 1,000,000 per return, with interest charges on late payments.\n\nDouble Taxation Agreements (DTAs) exist between Indonesia and many countries, which may reduce withholding tax rates on dividends, interest, and royalties paid to foreign shareholders. Understanding these treaty provisions is essential for optimizing the tax position of your PT PMA company.` },
  { id: 'hiring', title: 'Hiring Employees Legally', content: `Hiring employees in Indonesia requires compliance with the country's employment law framework, primarily governed by the Manpower Law (No. 13 of 2003) as amended by the Omnibus Law. Key requirements include written employment contracts, registration with social security programs (BPJS Kesehatan for health insurance and BPJS Ketenagakerjaan for employment benefits), and compliance with minimum wage regulations.\n\nBali's minimum wage (UMK) varies by regency but is generally in the range of IDR 2.8-3.1 million per month. However, skilled workers in tourism, technology, and professional services typically command significantly higher salaries based on experience and qualifications.\n\nForeign employees require a work permit and KITAS (Temporary Stay Permit), which must be sponsored by the employing PT PMA company. The company must demonstrate that the foreign worker fills a position that cannot be filled by an Indonesian national, and must commit to a knowledge transfer program. Each foreign employee may require a corresponding number of Indonesian employees in similar roles.\n\nEmployment contracts in Indonesia can be either fixed-term (PKWT) or permanent (PKWTT). Fixed-term contracts are limited to specific durations and can only be used for temporary, seasonal, or project-based work. Permanent contracts provide stronger employment protections and are required for ongoing core business positions.` },
  { id: 'office', title: 'Office Requirements in Bali', content: `Every company registered in Indonesia must have a domicile address for official correspondence and regulatory compliance. In Bali, companies can choose from several options including physical office space, co-working memberships, or virtual office services.\n\nVirtual office services are the most cost-effective option for companies that do not require a physical workspace. These services provide a registered business address, mail handling, phone answering, and access to meeting rooms when needed. Monthly costs range from IDR 500,000 to IDR 2,000,000 depending on the location and services included.\n\nPrime locations for business offices in Bali include Denpasar (the capital city with proximity to government offices), Seminyak and Canggu (popular with digital businesses and creative industries), Ubud (wellness and artisan businesses), and Sanur (established business district with international schools nearby).\n\nWhen selecting an office location, consider proximity to your target market, accessibility for both local and international clients, availability of reliable internet infrastructure, and the overall business ecosystem in the area. Some business licenses may require specific types of office arrangements depending on the nature of your activities.` },
  { id: 'costs', title: 'Costs of Starting a Company', content: `Starting a company in Bali involves several categories of costs that investors should plan for carefully. The total initial investment typically ranges from USD 5,000 to USD 15,000 for professional services and setup, plus the mandatory capital investment.\n\nRegistration and professional service fees (USD 2,000-5,000) cover company name reservation, notary fees, articles of association, Ministry approval, NPWP registration, and OSS/NIB licensing. These costs vary based on the complexity of the business structure and the service provider chosen.\n\nMandatory capital investment requires a minimum of IDR 2.5 billion (approximately USD 160,000) in paid-up capital for PT PMA companies. This capital is deposited into the company's bank account and can be used for business operations, equipment, and working capital.\n\nMonthly operational costs include virtual office rental (USD 30-100), basic accounting and tax compliance (USD 150-300), and various subscriptions and utilities. Annual compliance costs include financial audit fees (if required), annual reporting, and license renewals.\n\nAdditional costs may include KITAS processing for foreign directors (USD 1,000-2,500 annually), website and marketing setup, initial inventory or equipment, and employee salaries if hiring immediately. It is prudent to budget for 12-18 months of operational costs before expecting the business to generate sufficient revenue.` },
  { id: 'sectors', title: 'Business Sectors Open to Foreigners', content: `Indonesia's Positive Investment List (previously the Negative Investment List) defines which business sectors are open to foreign investment and the applicable ownership limits. Many sectors are now open to 100% foreign ownership following the Omnibus Law reforms.\n\nSectors commonly pursued by foreign investors in Bali include: technology and software development (100% foreign ownership), consulting and professional services (100%), tourism and hospitality (67-100% depending on category), restaurant and food service (100% for large-scale operations), education and training (49-67%), health and wellness (67-100%), and trading/e-commerce (100% for wholesale, restrictions on small-scale retail).\n\nSectors with restricted foreign ownership include: small-scale retail and traditional markets, certain media and broadcasting activities, small-scale tourism services, certain agricultural activities, and defense-related industries. Foreign investors should always verify current regulations as the investment list is updated periodically.\n\nHigh-growth sectors in Bali include digital services, wellness tourism, sustainable/eco-tourism, co-working and co-living spaces, food and beverage, creative industries, and renewable energy. These sectors benefit from Bali's unique market positioning and the growing international community on the island.` },
  { id: 'mistakes', title: 'Common Mistakes by Foreign Investors', content: `Foreign investors frequently make avoidable mistakes when setting up businesses in Bali. Understanding these common pitfalls can save significant time, money, and legal complications.\n\nUsing nominee arrangements is perhaps the most dangerous mistake. While some advisors may suggest using Indonesian nominees to circumvent foreign ownership restrictions, this practice is illegal under Indonesian law and can result in complete loss of your investment, criminal penalties, and deportation.\n\nSelecting incorrect KBLI codes is another common error that can lead to license denials, sector restriction violations, or the need for costly re-registration. Each KBLI code has specific implications for licensing, taxation, and foreign ownership limits.\n\nUnderestimating ongoing compliance costs catches many foreign entrepreneurs off guard. While the initial registration may seem affordable, monthly accounting, tax filing, annual reporting, and license maintenance create significant ongoing expenses that must be budgeted from the beginning.\n\nOther frequent mistakes include: trying to run a business on tourist visas (illegal and risky), not engaging qualified legal and tax advisors, failing to understand labor law requirements before hiring, mixing personal and company finances, and not maintaining proper records for tax audit purposes.\n\nFailing to plan for the time required is also common. The full process from planning to operational status typically takes 2-3 months, and rushing the process often leads to errors that cause further delays.` },
  { id: 'timeline', title: 'Timeline for Company Formation', content: `The complete timeline for establishing a PT PMA in Bali can be broken down into distinct phases, each with its own processing requirements and estimated duration.\n\nPhase 1 — Planning and Preparation (1-2 weeks): Business plan development, KBLI code research, capital planning, and service provider engagement. This phase is often rushed but is critical for avoiding costly errors later.\n\nPhase 2 — Name Reservation and Notary (1-2 weeks): Company name reservation through MENKUMHAM (1-3 days), drafting articles of association with the notary (3-5 days), and shareholder agreement preparation.\n\nPhase 3 — Legal Entity Registration (1-2 weeks): Submission to the Ministry of Law and Human Rights for approval, obtaining SK (decree) confirming legal entity status.\n\nPhase 4 — Tax and License Registration (1-2 weeks): NPWP tax registration (3-7 days), OSS registration and NIB (1-3 days), and sector-specific license applications (varies).\n\nPhase 5 — Operational Setup (1-2 weeks): Corporate bank account opening (1-2 weeks), capital deposit, office/virtual office setup, and initial compliance setup.\n\nTotal estimated timeline: 6-10 weeks from start to full operational status. This timeline assumes complete and correct documentation. Engaging experienced professionals typically results in the shorter end of this range.` },
  { id: 'faq', title: 'Frequently Asked Questions', content: `How much does it cost to start a business in Bali?\nTotal costs including professional services range from USD 5,000-15,000 plus mandatory capital investment starting at IDR 2.5 billion for PT PMA.\n\nCan I own 100% of my company as a foreigner?\nYes, in many sectors through PT PMA. Some sectors require Indonesian partners with specific ownership percentages.\n\nDo I need to live in Bali to run my company?\nNot necessarily, but you need a registered business address and should maintain regular presence. Foreign directors typically hold KITAS permits.\n\nWhat is the corporate tax rate?\nThe standard rate is 22%, with reductions available for qualifying small and medium enterprises.\n\nHow long does company registration take?\nTypically 6-10 weeks from planning to full operational status.\n\nCan I hire foreign employees?\nYes, PT PMA can sponsor KITAS work permits for foreign employees, subject to position requirements and quotas.\n\nWhat licenses do I need?\nAt minimum, NIB (Business Identification Number) through the OSS system. Additional licenses depend on your KBLI codes.\n\nIs a nominee arrangement safe?\nNo. Nominee arrangements are illegal in Indonesia and carry significant legal and financial risks.\n\nWhat business sectors are most profitable in Bali?\nDigital services, tourism, wellness, F&B, and co-working spaces are among the highest-growth sectors.\n\nWhere can I get visa help?\nVisa and immigration services are provided by Indonesian Visas Agency at indonesianvisas.com.` },
  { id: 'conclusion', title: 'Conclusion', content: `Starting a business in Bali is an achievable goal for foreign investors who approach the process with proper planning, adequate capital, and professional guidance. Indonesia's regulatory framework, while comprehensive, provides clear pathways for compliant business establishment and operation.\n\nThe key to success lies in understanding the legal requirements, engaging qualified professionals, budgeting realistically for both setup and ongoing costs, and maintaining full compliance with Indonesian regulations throughout the life of your business.\n\nBali Help, supported by PT Indonesian Visas Agency, is committed to helping foreign entrepreneurs navigate every step of this journey. From initial consultation and business planning through registration, licensing, and ongoing compliance support, our team provides the expertise needed to establish your business correctly from the start.\n\nFor visa and immigration services related to your business activities in Indonesia, visit Indonesian Visas Agency at indonesianvisas.com. For company formation and business licensing assistance, contact Bali Help through our website at balihelp.id or reach us directly on WhatsApp.` },
];

// Group guides by cluster for the index
const clusters = [
  { name: 'Company Formation', guides: GUIDES_DATA.filter(g => g.cluster === 'Company Formation') },
  { name: 'Business Licenses', guides: GUIDES_DATA.filter(g => g.cluster === 'Business Licenses') },
  { name: 'Tax & Compliance', guides: GUIDES_DATA.filter(g => g.cluster === 'Tax & Compliance') },
  { name: 'Doing Business in Bali', guides: GUIDES_DATA.filter(g => g.cluster === 'Doing Business in Bali') },
  { name: 'Corporate Structure', guides: GUIDES_DATA.filter(g => g.cluster === 'Corporate Structure') },
  { name: 'Comparison Guides', guides: GUIDES_DATA.filter(g => g.cluster === 'Comparison Guides') },
];

export default function UltimateGuidePage() {
  const articleSchema = {
    '@context': 'https://schema.org', '@type': 'Article',
    headline: 'How to Start a Business in Bali — Ultimate Guide',
    description: metadata.description,
    url: 'https://balihelp.id/business-guides/how-to-start-a-business-in-bali',
    publisher: { '@type': 'Organization', name: 'Bali Help', url: 'https://balihelp.id', logo: 'https://balihelp.id/Logo.webp' },
    provider: { '@type': 'Organization', name: 'PT Indonesian Visas Agency' },
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <div className="min-h-screen bg-white">
        <header className="border-b border-slate-200 bg-white sticky top-0 z-10">
          <nav className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <img src="/Logo.webp" alt="Bali Help company formation services" width={32} height={32} />
              <span className="text-lg font-bold text-slate-900">Bali Help</span>
            </Link>
            <div className="flex items-center gap-4 text-sm">
              <Link href="/csr" className="text-slate-600 hover:text-blue-600">CSR</Link>
              <Link href="/" className="text-slate-600 hover:text-blue-600">Home</Link>
            </div>
          </nav>
        </header>

        <main className="max-w-4xl mx-auto px-4 py-12">
          <nav aria-label="Breadcrumb" className="mb-8 text-sm text-slate-500">
            <ol className="flex items-center gap-2">
              <li><Link href="/" className="hover:text-blue-600">Home</Link></li>
              <li>/</li>
              <li className="text-slate-900 font-medium">Ultimate Business Guide</li>
            </ol>
          </nav>

          <article>
            <span className="inline-block px-3 py-1 text-xs font-semibold text-green-700 bg-green-50 rounded-full mb-4">Ultimate Guide</span>
            <h1 className="text-3xl md:text-5xl font-bold text-slate-900 mb-6 leading-tight">How to Start a Business in Bali</h1>
            <p className="text-xl text-slate-600 mb-10 leading-relaxed">The definitive guide to company formation, PT PMA registration, business licensing, and everything foreign investors need to know about starting a business in Bali, Indonesia.</p>

            {/* TOC */}
            <nav className="bg-slate-50 rounded-xl p-6 mb-12" aria-label="Table of contents">
              <h2 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Table of Contents</h2>
              <ol className="space-y-1 columns-1 md:columns-2">
                {sections.map((s, i) => (
                  <li key={s.id}><a href={`#${s.id}`} className="text-sm text-blue-600 hover:underline">{i + 1}. {s.title}</a></li>
                ))}
              </ol>
            </nav>

            {sections.map((section, i) => (
              <section key={section.id} id={section.id} className="mb-12">
                <h2 className="text-2xl font-bold text-slate-900 mb-4">{section.title}</h2>
                {section.content.split('\n\n').map((para, j) => (
                  <p key={j} className="text-slate-700 leading-relaxed text-base mb-4">{para}</p>
                ))}
              </section>
            ))}
          </article>

          {/* All Guides Index */}
          <aside className="border-t border-slate-200 pt-12 mb-12">
            <h2 className="text-2xl font-bold text-slate-900 mb-8">Business Knowledge Hub</h2>
            {clusters.map(c => (
              <div key={c.name} className="mb-8">
                <h3 className="text-lg font-semibold text-slate-700 mb-3">{c.name}</h3>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  {c.guides.map(g => (
                    <li key={g.slug}>
                      <Link href={`/business-guides/${g.slug}`} className="block p-3 bg-slate-50 rounded-lg hover:bg-blue-50 text-sm text-slate-800 hover:text-blue-700">
                        → {g.title}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </aside>

          {/* CTA */}
          <div className="bg-blue-600 text-white rounded-2xl p-8 text-center">
            <h2 className="text-2xl font-bold mb-3">Ready to Start Your Bali Business?</h2>
            <p className="mb-6 opacity-90">Bali Help provides expert company formation services for foreign investors.</p>
            <a href="https://wa.me/6285727041992" className="inline-block px-8 py-3 bg-white text-blue-700 font-bold rounded-lg hover:bg-slate-100">Contact Us on WhatsApp</a>
          </div>
        </main>

        <footer className="border-t border-slate-200 bg-slate-50 py-8 mt-12">
          <div className="max-w-4xl mx-auto px-4 text-sm text-slate-500">
            <strong className="text-slate-700">Bali Help</strong> — Operated by PT Indonesian Visas Agency.{' '}
            Visa services by <a href="https://indonesianvisas.com" className="text-blue-600 hover:underline">Indonesian Visas Agency</a>.
          </div>
        </footer>
      </div>
    </>
  );
}
